// AUTO-GENERATED by scripts/build-quran-content.ts. Do not edit.
import type { AyahText } from '../types';

import s001 from './001.json';
import s002 from './002.json';
import s003 from './003.json';
import s004 from './004.json';
import s005 from './005.json';
import s006 from './006.json';
import s007 from './007.json';
import s008 from './008.json';
import s009 from './009.json';
import s010 from './010.json';
import s011 from './011.json';
import s012 from './012.json';
import s013 from './013.json';
import s014 from './014.json';
import s015 from './015.json';
import s016 from './016.json';
import s017 from './017.json';
import s018 from './018.json';
import s019 from './019.json';
import s020 from './020.json';
import s021 from './021.json';
import s022 from './022.json';
import s023 from './023.json';
import s024 from './024.json';
import s025 from './025.json';
import s026 from './026.json';
import s027 from './027.json';
import s028 from './028.json';
import s029 from './029.json';
import s030 from './030.json';
import s031 from './031.json';
import s032 from './032.json';
import s033 from './033.json';
import s034 from './034.json';
import s035 from './035.json';
import s036 from './036.json';
import s037 from './037.json';
import s038 from './038.json';
import s039 from './039.json';
import s040 from './040.json';
import s041 from './041.json';
import s042 from './042.json';
import s043 from './043.json';
import s044 from './044.json';
import s045 from './045.json';
import s046 from './046.json';
import s047 from './047.json';
import s048 from './048.json';
import s049 from './049.json';
import s050 from './050.json';
import s051 from './051.json';
import s052 from './052.json';
import s053 from './053.json';
import s054 from './054.json';
import s055 from './055.json';
import s056 from './056.json';
import s057 from './057.json';
import s058 from './058.json';
import s059 from './059.json';
import s060 from './060.json';
import s061 from './061.json';
import s062 from './062.json';
import s063 from './063.json';
import s064 from './064.json';
import s065 from './065.json';
import s066 from './066.json';
import s067 from './067.json';
import s068 from './068.json';
import s069 from './069.json';
import s070 from './070.json';
import s071 from './071.json';
import s072 from './072.json';
import s073 from './073.json';
import s074 from './074.json';
import s075 from './075.json';
import s076 from './076.json';
import s077 from './077.json';
import s078 from './078.json';
import s079 from './079.json';
import s080 from './080.json';
import s081 from './081.json';
import s082 from './082.json';
import s083 from './083.json';
import s084 from './084.json';
import s085 from './085.json';
import s086 from './086.json';
import s087 from './087.json';
import s088 from './088.json';
import s089 from './089.json';
import s090 from './090.json';
import s091 from './091.json';
import s092 from './092.json';
import s093 from './093.json';
import s094 from './094.json';
import s095 from './095.json';
import s096 from './096.json';
import s097 from './097.json';
import s098 from './098.json';
import s099 from './099.json';
import s100 from './100.json';
import s101 from './101.json';
import s102 from './102.json';
import s103 from './103.json';
import s104 from './104.json';
import s105 from './105.json';
import s106 from './106.json';
import s107 from './107.json';
import s108 from './108.json';
import s109 from './109.json';
import s110 from './110.json';
import s111 from './111.json';
import s112 from './112.json';
import s113 from './113.json';
import s114 from './114.json';

export const surahs: Record<number, AyahText[]> = {
  1: s001,
  2: s002,
  3: s003,
  4: s004,
  5: s005,
  6: s006,
  7: s007,
  8: s008,
  9: s009,
  10: s010,
  11: s011,
  12: s012,
  13: s013,
  14: s014,
  15: s015,
  16: s016,
  17: s017,
  18: s018,
  19: s019,
  20: s020,
  21: s021,
  22: s022,
  23: s023,
  24: s024,
  25: s025,
  26: s026,
  27: s027,
  28: s028,
  29: s029,
  30: s030,
  31: s031,
  32: s032,
  33: s033,
  34: s034,
  35: s035,
  36: s036,
  37: s037,
  38: s038,
  39: s039,
  40: s040,
  41: s041,
  42: s042,
  43: s043,
  44: s044,
  45: s045,
  46: s046,
  47: s047,
  48: s048,
  49: s049,
  50: s050,
  51: s051,
  52: s052,
  53: s053,
  54: s054,
  55: s055,
  56: s056,
  57: s057,
  58: s058,
  59: s059,
  60: s060,
  61: s061,
  62: s062,
  63: s063,
  64: s064,
  65: s065,
  66: s066,
  67: s067,
  68: s068,
  69: s069,
  70: s070,
  71: s071,
  72: s072,
  73: s073,
  74: s074,
  75: s075,
  76: s076,
  77: s077,
  78: s078,
  79: s079,
  80: s080,
  81: s081,
  82: s082,
  83: s083,
  84: s084,
  85: s085,
  86: s086,
  87: s087,
  88: s088,
  89: s089,
  90: s090,
  91: s091,
  92: s092,
  93: s093,
  94: s094,
  95: s095,
  96: s096,
  97: s097,
  98: s098,
  99: s099,
  100: s100,
  101: s101,
  102: s102,
  103: s103,
  104: s104,
  105: s105,
  106: s106,
  107: s107,
  108: s108,
  109: s109,
  110: s110,
  111: s111,
  112: s112,
  113: s113,
  114: s114,
};

export const loadSurah = (id: number): AyahText[] | undefined => surahs[id];
