// Bundled content types. SPEC §8.1, §8.2, §8.4.
// Files under src/content/ are generated by scripts/build-quran-content.ts.
// Never hand-edit — pipeline is the source of truth (SPEC §28.1).

export type RevelationPlace = 'makkah' | 'madinah';

export interface SurahMeta {
  id: number;
  nameArabic: string;
  nameTransliterated: string;
  nameFrench: string;
  ayahCount: number;
  revelationPlace: RevelationPlace;
}

export interface AyahText {
  ayah: number;
  text: string;
}

export interface AyahIndexEntry {
  juz: number;
  hizbQuarter: number;
  page: number;
}

export type AyahIndex = Record<string, AyahIndexEntry>;
